# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - soconnor73
  categories:
    - title: Features and Enhancements
      labels:
        - Semver-Major
        - enhancement
    - title: Bug Fixes
      labels:
        - Semver-Minor
        - bug
    - title: Other Changes
      labels:
        - "*"
