name: Build CMINFO and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # This is important to fetch all history for all tags

      - name: Set up Python 3.13
        id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        id: install_dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PyInstaller
        id: run_pyinstaller
        run: |
          pip install pyinstaller
          pyinstaller --onefile -i ./images/logo.ico -n cminfo-linux ./cminfo.py

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release for version ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/work/ciphertrust-info/ciphertrust-info/build/cminfo-linux/cminfo-linux
          asset_name: cminfo-linux
          asset_content_type: application/octet-stream
